baseURL = "https://vhascoet-pro.github.io/portfolio-bts.github.io/"
languageCode = 'fr'
title = 'Portfolio'
theme = 'terminal'

[[menu.main]]
  name = "A propos"
  url = "/about"

[[menu.main]]
  name = "Page des certifications"
  url = "/certif"

[[menu.main]]
  name = "Veille Technologique"
  url = "/vtechno/VTECH1"

[[menu.main]]
  name = "Rapport d'activités 2024"
  url = "/RDS1/RDS1_1"

[[menu.main]]
  name = "Rapport d'activités 2025"
  url = "/RDS2/RDS2_1"

[[menu.footer]]
  name = "A propos"
  url = "/about"

[markup.goldmark.renderer]
  unsafe= true

[params]
  enableEmoji= true
  themeColor = "green"
  fullWidthTheme = true
  updatedDatePrefix = "Mis à jour"
  Toc = false
  TocTitle = "Index"
  
[languages]
  [languages.fr]
    [languages.fr.params]
      languageName = "Français"
      title = "Portfolio"
      owner = "Vincent Hascoët"
      copyright = "(2023 - 2025) - Hascoët Vincent"
      missingContentMessage = "Page non trouvée..."
      missingBackButtonLabel = "Retour à l'accueil"

    [languages.en.params.logo]
      logoText = "Portfolio"
      logoHomeLink = "https://vhascoet-pro.github.io/portfolio-bts.github.io/"
